apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastflag
  name: fastflag
spec:
  loadBalancerIP: 35.185.212.201
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: fastflag
  type: LoadBalancer
