apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsaos
  name: rsaos
spec:
  loadBalancerIP: 35.197.48.181
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: rsaos
  type: LoadBalancer
