apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloud2clown
    tier: challenge
  name: cloud2clown
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: cloud2clown
        networkpolicy: deny_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2019/cloud2clown
        name: cloud2clown
        ports:
        - containerPort: 8081
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      - env:
        - name: COOKIES
          value: AUTHZ_KEY=correct horse battery staple; url=https://cloud2clown-dc9b5aed.challenges.bsidessf.net/
        - name: TARGET_URIS
          value: https://cloud2clown-dc9b5aed.challenges.bsidessf.net/review
        image: gcr.io/bsides-sf-ctf-2019/webbot:latest
        name: webbot
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      volumes: []
