apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud2clown
  name: cloud2clown
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cloud2clown
  type: NodePort
