apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythia
  name: pythia
spec:
  loadBalancerIP: 35.197.106.220
  ports:
  - port: 1521
    protocol: TCP
    targetPort: 1521
  selector:
    app: pythia
  type: LoadBalancer
