apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: crust
    tier: challenge
  name: crust
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: crust
        networkpolicy: deny_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2019/crust
        name: crust
        ports:
        - containerPort: 53535
          protocol: UDP
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
