apiVersion: v1
kind: Service
metadata:
  labels:
    app: crust
  name: crust
spec:
  loadBalancerIP: 35.197.81.243
  ports:
  - port: 53535
    protocol: UDP
    targetPort: 53535
  selector:
    app: crust
  type: LoadBalancer
