apiVersion: v1
kind: Service
metadata:
  labels:
    app: svgmagic
  name: svgmagic
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: svgmagic
  type: NodePort
