apiVersion: v1
kind: Service
metadata:
  labels:
    app: pick-tac-toe
  name: pick-tac-toe
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pick-tac-toe
  type: NodePort
