apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: water-dragon
    tier: challenge
  name: water-dragon
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: water-dragon
        networkpolicy: deny_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2019/water-dragon
        name: water-dragon
        ports:
        - containerPort: 1901
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
