apiVersion: v1
kind: Service
metadata:
  labels:
    app: water-dragon
  name: water-dragon
spec:
  loadBalancerIP: 35.185.232.193
  ports:
  - port: 1901
    protocol: TCP
    targetPort: 1901
  selector:
    app: water-dragon
  type: LoadBalancer
