apiVersion: v1
kind: Service
metadata:
  labels:
    app: genius
  name: genius
spec:
  loadBalancerIP: 35.197.15.138
  ports:
  - port: 1338
    protocol: TCP
    targetPort: 1338
  selector:
    app: genius
  type: LoadBalancer
