apiVersion: v1
kind: Service
metadata:
  name: runitplusplus
  labels:
    app: runitplusplus
spec:
  type: LoadBalancer
  ports:
      - port: 5353
        targetPort: 5353
  selector:
    app: runitplusplus
