apiVersion: v1
kind: Service
metadata:
  labels:
    app: mainframe
  name: mainframe
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mainframe
  type: NodePort
