apiVersion: v1
kind: Service
metadata:
  labels:
    app: runitplusplus
  name: runitplusplus
spec:
  loadBalancerIP: 35.197.87.99
  ports:
  - port: 5353
    protocol: TCP
    targetPort: 5353
  selector:
    app: runitplusplus
  type: LoadBalancer
