apiVersion: v1
kind: Service
metadata:
  labels:
    app: decrypto
  name: decrypto
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: decrypto
  type: NodePort
